name: manifest-guard
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  manifest-guard:
    uses: codefly-dev/.github/.github/workflows/plugin-manifest-guard.yml@78f7890b3e55f420a7d16b2b3e3e655c25e16cc8 # main
